name: Test

on:
  push:
    tags-ignore:
      - '*DB*'
env:
  artifact: 1
  TEST: 1

jobs:
  osx_job:
    runs-on: macos-latest
    env:
      BOOST_ROOT: /tmp/boost
    steps:
      - uses: actions/checkout@5a4ac90
        with:
          submodules: "recursive"
      - uses: chrislennon/action-aws-cli@f0f8671
      - name: tag
        run: |
          TAG=`git describe --tags $GITHUB_SHA`
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Fetch Deps
        run: ci/actions/osx/install_deps.sh
      - name: Build Artifact
        run: TRAVIS_TAG=${TAG} ci/build-deploy.sh "/tmp/qt/lib/cmake/Qt5";            
      - name: Deploy Artifact
        run: ci/actions/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
  
  linux_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@5a4ac90
        with:
          submodules: "recursive"
      - uses: chrislennon/action-aws-cli@f0f8671
      - name: tag
        run: |
          TAG=`git describe --tags $GITHUB_SHA`
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh
      - name: Build Artifact
        run: docker run -e TEST -v ${GITHUB_WORKSPACE}:/workspace nanocurrency/nano-env:gcc /bin/bash -c "cd /workspace && TRAVIS_TAG=${TAG} ci/build-deploy.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5 ${PWD}"
      - name: Deploy Artifact
        run: ci/actions/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2     

  linux_docker_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@5a4ac90
        with:
          submodules: "recursive"
      - uses: chrislennon/action-aws-cli@f0f8671
      - name: tag
        run: |
          TAG=`git describe --tags $GITHUB_SHA`
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh
      - name: Deploy Docker (nanocurrency/nano)
        run: TRAVIS_TAG=${TAG} ci/actions/linux/deploy-docker.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to ghcr.io
        uses: docker/login-action@adb7347
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Deploy Docker (ghcr.io)
        run: ci/actions/linux/ghcr_push.sh

  windows_job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@5a4ac90
        with:
          submodules: "recursive"
      - uses: chrislennon/action-aws-cli@f0f8671
      - name: tag
        run: |
          $TAG=git describe --tags $GITHUB_SHA
          echo "TAG=$TAG" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Fetch Deps
        run: ci/actions/windows/install_deps.ps1
      - name: Build Artifact
        run: ci/actions/windows/build.ps1
        env: 
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      - name: Deploy Artifact
        run: ci/actions/windows/deploy.ps1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2